server:
  error:
    path: /error2
  port: 8082
spring:
  application:
    name: Bootstrap Spring Boot in dev
  banner:
    location: classpath:my-banner.txt
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  output:
    ansi:
      enabled: always
  security:
    user:
      name: user
      password: password
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
# log level

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework.test: ERROR
    com.example.demo: INFO
    org.hibernate: INFO
    org.apache.http.wire: INFO
